version: '3.4'

services:
  
  catalogdb:
    image: mongo
    container_name: catalogdb
    restart: always
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - matoa
         
  
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    container_name: catalogapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://catalogdb:27017"
    ports:
      - "8000:80"
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
    depends_on:
      - catalogdb
    networks:
      - matoa
    
volumes:
  mongo_data:
networks:
  matoa:
    driver: bridge